{% set name = "tomviz" %}
{% set version = "2.1.0" %}
{% set paraview_version = "6.0.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/danlipsa/tomviz
    git_rev: paraview_upgrade
    folder: tomviz
  # Submodules updated in build.sh: pybind11

  - git_url: https://gitlab.kitware.com/paraview/paraview.git
    git_rev: v6.0.0
    folder: paraview
  # Submodules updated in build.sh: VTK, VisItBridge, QtTesting, catalyst

build:
  number: 0


requirements:
  build:
    - cmake
    - ninja
    - pkg-config
    - git-lfs
    - tbb-devel
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - py3c
    - libgl-devel  # [linux]
    - libegl-devel  # [linux]
    - libglvnd-devel  # [linux]
    - qt6-main>=6.9.3
    - libprotobuf
    - cgns
    - libboost-headers
    - libzip
    - libcurl
    - icu
    - libharu
    - libxml2-devel 2.14*
    - tbb-devel
  run:
    - python
    - numpy
    - scipy
    - marshmallow
    - jsonpatch
    - jsonpointer
    - pyfftw
    - pygments
test:
  imports:
    - paraview

about:
  home: https://github.com/OpenChemistry/tomviz
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - tomviz/LICENSE
  summary: 'Cross platform, open source application for the processing, visualization, and analysis of 3D tomography data'
  doc_url: https://tomviz.readthedocs.io/
  dev_url: https://github.com/OpenChemistry/tomviz

extra:
  recipe-maintainers:
    - cjh1
    - conda-forge/event-model
